"""add early_confirm_guard_hours

Revision ID: 57cb21625dd0
Revises: 63e78092605e
Create Date: 2026-09-09 12:32:04.769950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57cb21625dd0'
down_revision: Union[str, None] = '63e78092605e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'habits',
        sa.Column('early_confirm_guard_hours', sa.Integer(), nullable=False, server_default='3'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'early_confirm_guard_hours')
    # ### end Alembic commands ###
