"""create habits and occurrences

Revision ID: 63e78092605e
Revises: 
Create Date: 2026-09-08 22:59:08.493335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63e78092605e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('medication', 'gym', 'custom', name='habittype'), nullable=False),
    sa.Column('times', sa.JSON(), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('retry_interval_min', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'notified', 'confirmed', 'missed', name='occurrencestatus'), nullable=False),
    sa.Column('notify_count', sa.Integer(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'scheduled_at', name='uq_habit_scheduled_at')
    )
    op.create_index(op.f('ix_occurrences_habit_id'), 'occurrences', ['habit_id'], unique=False)
    op.create_index(op.f('ix_occurrences_scheduled_at'), 'occurrences', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_occurrences_status'), 'occurrences', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_status'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_scheduled_at'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_habit_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_table('habits')
    # ### end Alembic commands ###
